workflows:

  generate-keystore:

    name: Générer keystore Android

    max_build_duration: 10

    instance_type: mac_mini_m2

    environment:
      node: 22
      java: 21

      vars:
        KEYSTORE_NAME: "partenairefoyer.keystore"
        KEY_ALIAS: "partenairefoyer"
        KEYSTORE_PASSWORD: "ChangeMoi123!"
        KEY_PASSWORD: "ChangeMoi123!"

    scripts:

      - name: Générer le keystore
        script: |
          keytool \
            -genkeypair \
            -v \
            -keystore "$KEYSTORE_NAME" \
            -storetype JKS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias "$KEY_ALIAS" \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=PartenaireFoyer, OU=SiteToApp, O=PartenaireFoyer, L=Bouvron, ST=Loire-Atlantique, C=FR"

      - name: Vérifier le keystore
        script: |
          keytool \
            -list \
            -v \
            -keystore "$KEYSTORE_NAME" \
            -storepass "$KEYSTORE_PASSWORD"

    artifacts:
      - partenairefoyer.keystore
